### ISSUE TITLE
'dmtx.h' file not found

### ISSUE THREAD

**Issue by lgomez** [GuillaumeZuff/dmCreator#1]
Hello there. Sorry to bother...

I was hoping to try this module but I seem to be hitting the same issue over and over (not a C++ developer). I keep getting this error:

```
../src/datamatrix.cpp:2:10: fatal error: 'dmtx.h' file not found
```
When running `npm I` on a fresh clone of this repo.

Originally I thought it'd be related to not having Xcode installed but I installed it, agreed to the terms, etc and keep getting the same error.

If you don't mind, could you point me in the right direction so I can work on solving this?

Thank you

**Comment by GuillaumeZuff** [comment]
Hello,

Sorry the readme should be more complete: you need to install libdmtx separately to use the module. You'll find some instructions on how to do it [here](http://libdmtx.wikidot.com/general-instructions).

I hope that it helps, don't hesitate if you have other questions/issues.
